services:
  postgres:
    image: postgis/postgis:18-3.6
    container_name: atlas-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-atlas}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-atlas}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - atlas-network

networks:
  atlas-network:
    driver: bridge

volumes:
  postgres_data:
    name: atlas-postgres-data

