run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam
    - gosec
    - bodyclose
    - copyloopvar
    - gocritic
    - nilerr
    - predeclared
    - sqlclosecheck
    - tparallel
    - unconvert
    - wastedassign

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/sean/atlas/api
  
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: indent-error-flow
        severity: warning
      - name: error-return
        severity: warning
      - name: error-naming
        severity: warning
  
  gosec:
    excludes:
      - G404 # Use of weak random number generator (math/rand instead of crypto/rand)
    severity: medium
    confidence: medium

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - unparam

